name: eva_connector
description: A sample command-line application.
version: 0.3.5
# repository: https://github.com/my_org/my_repo

environment:
  sdk: ^3.10.0

dependencies:
  yaml_writer: ^2.1.0
  yaml: ^3.1.3
  dartssh2: ^2.12.0
  msgpack_dart: ^1.0.1
  busrt_client: ^0.4.0

dev_dependencies:
  lints: ^6.0.0
  test: ^1.24.0
